version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - labnet

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    command: ["-c", "/etc/suricata/suricata.yaml", "-i", "eth0"]
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/logs:/var/log/suricata
      - ./suricata/rules:/etc/suricata/rules
    networks:
      - labnet
    depends_on:
      - mosquitto

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./suricata/logs:/var/log/suricata:ro
    networks:
      - labnet
    depends_on:
      - suricata

networks:
  labnet:
    driver: bridge
